#Workaround to unexpected EOF error

# Problem #

If you get the error output like below, please read this article.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyvtk/__init__.py", line 129, in __init__
    self.fromfile(args[0])
  File "/usr/local/lib/python2.7/dist-packages/pyvtk/__init__.py", line 222, in fromfile
    self.structure,l = ff(f,self)
  File "/usr/local/lib/python2.7/dist-packages/pyvtk/PolyData.py", line 97, in polydata_fromfile
    points += map(eval,l.split(' '))
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing

```

# Cause #

The reason is self-explanatory in the error prompt. Older versions of pyvtk only allows VTK files where multiple values in one line to be separated by single space. If not (e.g., in VTK files generated by [FreeSurfer/mris\_convert](http://surfer.nmr.mgh.harvard.edu/fswiki/mris_convert)), you will see this error.

However, VTK format specification seems missed to specify what strings are allowed to separate same-line values in a VTK file. Should tabs or triple spaces be allowed?

# Workaround #

Open the `PolyData.py` source code file, and replace all `split(' ')` by `split()`. I am not sure whether this modification has no side effect. It is NOT tested. That's why I didn't push the change into Git. Please let me know if you have new troubles due to this change.